name: Generate JSDoc

on:
  push:
    branches: [main]

jobs:
  jsdoc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install dependencies
        working-directory: ./source
        run: npm install

      - name: Generate JSDoc
        working-directory: ./source
        run: npm run docs
